-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:af111c1c60e20e00017cae0c8fa37aa1$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "pi_connect1",
				spriteColorRect = { x = 212, y = 142, width = 124, height = 98 },
				textureRect = { x = 258, y = 324, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect2",
				spriteColorRect = { x = 215, y = 144, width = 118, height = 94 },
				textureRect = { x = 392, y = 220, width = 118, height = 94 },
				spriteSourceSize = { width = 118, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect3",
				spriteColorRect = { x = 210, y = 139, width = 128, height = 102 },
				textureRect = { x = 262, y = 220, width = 128, height = 102 },
				spriteSourceSize = { width = 128, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect4",
				spriteColorRect = { x = 206, y = 134, width = 138, height = 110 },
				textureRect = { x = 144, y = 2, width = 138, height = 110 },
				spriteSourceSize = { width = 138, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect5",
				spriteColorRect = { x = 208, y = 137, width = 134, height = 106 },
				textureRect = { x = 284, y = 112, width = 134, height = 106 },
				spriteSourceSize = { width = 134, height = 106 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect6",
				spriteColorRect = { x = 210, y = 138, width = 130, height = 104 },
				textureRect = { x = 136, y = 114, width = 130, height = 104 },
				spriteSourceSize = { width = 130, height = 104 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect7",
				spriteColorRect = { x = 210, y = 141, width = 128, height = 100 },
				textureRect = { x = 2, y = 324, width = 128, height = 100 },
				spriteSourceSize = { width = 128, height = 100 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect8",
				spriteColorRect = { x = 212, y = 142, width = 124, height = 98 },
				textureRect = { x = 258, y = 324, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi_connect9",
				spriteColorRect = { x = 212, y = 142, width = 124, height = 98 },
				textureRect = { x = 258, y = 324, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect1",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 132, y = 324, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect2",
				spriteColorRect = { x = 214, y = 143, width = 120, height = 94 },
				textureRect = { x = 128, y = 624, width = 120, height = 94 },
				spriteSourceSize = { width = 120, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect3",
				spriteColorRect = { x = 211, y = 139, width = 128, height = 102 },
				textureRect = { x = 132, y = 220, width = 128, height = 102 },
				spriteSourceSize = { width = 128, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect4",
				spriteColorRect = { x = 205, y = 134, width = 140, height = 110 },
				textureRect = { x = 2, y = 2, width = 140, height = 110 },
				spriteSourceSize = { width = 140, height = 110 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect5",
				spriteColorRect = { x = 206, y = 135, width = 136, height = 108 },
				textureRect = { x = 284, y = 2, width = 136, height = 108 },
				spriteSourceSize = { width = 136, height = 108 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect6",
				spriteColorRect = { x = 208, y = 138, width = 132, height = 104 },
				textureRect = { x = 2, y = 114, width = 132, height = 104 },
				spriteSourceSize = { width = 132, height = 104 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect7",
				spriteColorRect = { x = 211, y = 139, width = 128, height = 102 },
				textureRect = { x = 2, y = 220, width = 128, height = 102 },
				spriteSourceSize = { width = 128, height = 102 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect8",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 132, y = 324, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime_connect9",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 132, y = 324, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect1",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 380, y = 524, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect2",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 254, y = 524, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect3",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 2, y = 526, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect4",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 128, y = 524, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect5",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 384, y = 424, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect6",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 258, y = 424, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect7",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 2, y = 426, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect8",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 132, y = 424, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "wait_connect9",
				spriteColorRect = { x = 213, y = 142, width = 124, height = 98 },
				textureRect = { x = 384, y = 324, width = 124, height = 98 },
				spriteSourceSize = { width = 124, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			}
		}
	}
end
return SpriteSheet

