-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:8a19429a8ae0ed498e7af82e5706584c$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "login_anim1",
				spriteColorRect = { x = 52, y = 261, width = 526, height = 526 },
				textureRect = { x = 2, y = 532, width = 526, height = 526 },
				spriteSourceSize = { width = 526, height = 526 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim2",
				spriteColorRect = { x = 52, y = 259, width = 526, height = 528 },
				textureRect = { x = 2, y = 2, width = 526, height = 528 },
				spriteSourceSize = { width = 526, height = 528 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim3",
				spriteColorRect = { x = 68, y = 277, width = 494, height = 494 },
				textureRect = { x = 1392, y = 2, width = 494, height = 494 },
				spriteSourceSize = { width = 494, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim4",
				spriteColorRect = { x = 79, y = 288, width = 472, height = 472 },
				textureRect = { x = 530, y = 492, width = 472, height = 472 },
				spriteSourceSize = { width = 472, height = 472 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim5",
				spriteColorRect = { x = 87, y = 296, width = 458, height = 458 },
				textureRect = { x = 2, y = 1586, width = 458, height = 458 },
				spriteSourceSize = { width = 458, height = 458 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim6",
				spriteColorRect = { x = 88, y = 297, width = 454, height = 454 },
				textureRect = { x = 462, y = 1586, width = 454, height = 454 },
				spriteSourceSize = { width = 454, height = 454 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim7",
				spriteColorRect = { x = 79, y = 288, width = 472, height = 472 },
				textureRect = { x = 918, y = 1568, width = 472, height = 472 },
				spriteSourceSize = { width = 472, height = 472 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim8",
				spriteColorRect = { x = 69, y = 280, width = 490, height = 488 },
				textureRect = { x = 530, y = 2, width = 490, height = 488 },
				spriteSourceSize = { width = 490, height = 488 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim9",
				spriteColorRect = { x = 61, y = 270, width = 506, height = 506 },
				textureRect = { x = 528, y = 1060, width = 506, height = 506 },
				spriteSourceSize = { width = 506, height = 506 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim10",
				spriteColorRect = { x = 53, y = 263, width = 524, height = 524 },
				textureRect = { x = 2, y = 1060, width = 524, height = 524 },
				spriteSourceSize = { width = 524, height = 524 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim11",
				spriteColorRect = { x = 83, y = 293, width = 462, height = 462 },
				textureRect = { x = 1036, y = 1010, width = 462, height = 462 },
				spriteSourceSize = { width = 462, height = 462 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim12",
				spriteColorRect = { x = 116, y = 323, width = 398, height = 398 },
				textureRect = { x = 1004, y = 610, width = 398, height = 398 },
				spriteSourceSize = { width = 398, height = 398 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim13",
				spriteColorRect = { x = 148, y = 356, width = 334, height = 334 },
				textureRect = { x = 1036, y = 2, width = 334, height = 334 },
				spriteSourceSize = { width = 334, height = 334 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim14",
				spriteColorRect = { x = 180, y = 388, width = 270, height = 270 },
				textureRect = { x = 1036, y = 338, width = 270, height = 270 },
				spriteSourceSize = { width = 270, height = 270 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim15",
				spriteColorRect = { x = 212, y = 421, width = 206, height = 206 },
				textureRect = { x = 1404, y = 498, width = 206, height = 206 },
				spriteSourceSize = { width = 206, height = 206 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim16",
				spriteColorRect = { x = 244, y = 452, width = 142, height = 142 },
				textureRect = { x = 1888, y = 2, width = 142, height = 142 },
				spriteSourceSize = { width = 142, height = 142 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim17",
				spriteColorRect = { x = 276, y = 485, width = 78, height = 78 },
				textureRect = { x = 1888, y = 146, width = 78, height = 78 },
				spriteSourceSize = { width = 78, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim18",
				spriteColorRect = { x = 308, y = 517, width = 14, height = 14 },
				textureRect = { x = 528, y = 1568, width = 14, height = 14 },
				spriteSourceSize = { width = 14, height = 14 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim17",
				spriteColorRect = { x = 276, y = 485, width = 78, height = 78 },
				textureRect = { x = 1888, y = 146, width = 78, height = 78 },
				spriteSourceSize = { width = 78, height = 78 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim16",
				spriteColorRect = { x = 244, y = 452, width = 142, height = 142 },
				textureRect = { x = 1888, y = 2, width = 142, height = 142 },
				spriteSourceSize = { width = 142, height = 142 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim15",
				spriteColorRect = { x = 212, y = 421, width = 206, height = 206 },
				textureRect = { x = 1404, y = 498, width = 206, height = 206 },
				spriteSourceSize = { width = 206, height = 206 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim14",
				spriteColorRect = { x = 180, y = 388, width = 270, height = 270 },
				textureRect = { x = 1036, y = 338, width = 270, height = 270 },
				spriteSourceSize = { width = 270, height = 270 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim13",
				spriteColorRect = { x = 148, y = 356, width = 334, height = 334 },
				textureRect = { x = 1036, y = 2, width = 334, height = 334 },
				spriteSourceSize = { width = 334, height = 334 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim12",
				spriteColorRect = { x = 116, y = 323, width = 398, height = 398 },
				textureRect = { x = 1004, y = 610, width = 398, height = 398 },
				spriteSourceSize = { width = 398, height = 398 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim11",
				spriteColorRect = { x = 83, y = 293, width = 462, height = 462 },
				textureRect = { x = 1036, y = 1010, width = 462, height = 462 },
				spriteSourceSize = { width = 462, height = 462 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim10",
				spriteColorRect = { x = 53, y = 263, width = 524, height = 524 },
				textureRect = { x = 2, y = 1060, width = 524, height = 524 },
				spriteSourceSize = { width = 524, height = 524 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim9",
				spriteColorRect = { x = 61, y = 270, width = 506, height = 506 },
				textureRect = { x = 528, y = 1060, width = 506, height = 506 },
				spriteSourceSize = { width = 506, height = 506 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim8",
				spriteColorRect = { x = 69, y = 280, width = 490, height = 488 },
				textureRect = { x = 530, y = 2, width = 490, height = 488 },
				spriteSourceSize = { width = 490, height = 488 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim7",
				spriteColorRect = { x = 79, y = 288, width = 472, height = 472 },
				textureRect = { x = 918, y = 1568, width = 472, height = 472 },
				spriteSourceSize = { width = 472, height = 472 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim6",
				spriteColorRect = { x = 88, y = 297, width = 454, height = 454 },
				textureRect = { x = 462, y = 1586, width = 454, height = 454 },
				spriteSourceSize = { width = 454, height = 454 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim5",
				spriteColorRect = { x = 87, y = 296, width = 458, height = 458 },
				textureRect = { x = 2, y = 1586, width = 458, height = 458 },
				spriteSourceSize = { width = 458, height = 458 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim4",
				spriteColorRect = { x = 79, y = 288, width = 472, height = 472 },
				textureRect = { x = 530, y = 492, width = 472, height = 472 },
				spriteSourceSize = { width = 472, height = 472 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim3",
				spriteColorRect = { x = 68, y = 277, width = 494, height = 494 },
				textureRect = { x = 1392, y = 2, width = 494, height = 494 },
				spriteSourceSize = { width = 494, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim2",
				spriteColorRect = { x = 52, y = 259, width = 526, height = 528 },
				textureRect = { x = 2, y = 2, width = 526, height = 528 },
				spriteSourceSize = { width = 526, height = 528 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "login_anim1",
				spriteColorRect = { x = 52, y = 261, width = 526, height = 526 },
				textureRect = { x = 2, y = 532, width = 526, height = 526 },
				spriteSourceSize = { width = 526, height = 526 },
				spriteTrimmed = false,
				textureRotated = false
			}
		}
	}
end
return SpriteSheet

