-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:c8524bf04d7e80b219ffe6ca1fdb4bfb$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "pi1",
				spriteColorRect = { x = 10, y = 15, width = 339, height = 421 },
				textureRect = { x = 2, y = 820, width = 339, height = 421 },
				spriteSourceSize = { width = 339, height = 421 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2",
				spriteColorRect = { x = 9, y = 18, width = 341, height = 419 },
				textureRect = { x = 1384, y = 415, width = 341, height = 419 },
				spriteSourceSize = { width = 341, height = 419 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3",
				spriteColorRect = { x = 8, y = 21, width = 343, height = 415 },
				textureRect = { x = 351, y = 407, width = 343, height = 415 },
				spriteSourceSize = { width = 343, height = 415 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi4",
				spriteColorRect = { x = 7, y = 22, width = 345, height = 415 },
				textureRect = { x = 696, y = 411, width = 345, height = 415 },
				spriteSourceSize = { width = 345, height = 415 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi5",
				spriteColorRect = { x = 5, y = 26, width = 347, height = 411 },
				textureRect = { x = 2, y = 407, width = 347, height = 411 },
				spriteSourceSize = { width = 347, height = 411 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi6",
				spriteColorRect = { x = 6, y = 28, width = 347, height = 409 },
				textureRect = { x = 1047, y = 2, width = 347, height = 409 },
				spriteSourceSize = { width = 347, height = 409 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi7",
				spriteColorRect = { x = 5, y = 30, width = 349, height = 407 },
				textureRect = { x = 696, y = 2, width = 349, height = 407 },
				spriteSourceSize = { width = 349, height = 407 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi8",
				spriteColorRect = { x = 5, y = 34, width = 349, height = 403 },
				textureRect = { x = 345, y = 2, width = 349, height = 403 },
				spriteSourceSize = { width = 349, height = 403 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-1",
				spriteColorRect = { x = 4, y = 30, width = 340, height = 422 },
				textureRect = { x = 684, y = 828, width = 340, height = 422 },
				spriteSourceSize = { width = 340, height = 422 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-2",
				spriteColorRect = { x = 8, y = 20, width = 336, height = 432 },
				textureRect = { x = 1706, y = 836, width = 336, height = 432 },
				spriteSourceSize = { width = 336, height = 432 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-3",
				spriteColorRect = { x = 11, y = 10, width = 338, height = 442 },
				textureRect = { x = 2, y = 1243, width = 338, height = 442 },
				spriteSourceSize = { width = 338, height = 442 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-4",
				spriteColorRect = { x = 16, y = 1, width = 348, height = 450 },
				textureRect = { x = 683, y = 1257, width = 348, height = 450 },
				spriteSourceSize = { width = 348, height = 450 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-1",
				spriteColorRect = { x = 10, y = 15, width = 339, height = 421 },
				textureRect = { x = 343, y = 824, width = 339, height = 421 },
				spriteSourceSize = { width = 339, height = 421 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-2",
				spriteColorRect = { x = 11, y = 21, width = 339, height = 417 },
				textureRect = { x = 1043, y = 413, width = 339, height = 417 },
				spriteSourceSize = { width = 339, height = 417 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-3",
				spriteColorRect = { x = 10, y = 27, width = 341, height = 411 },
				textureRect = { x = 1396, y = 2, width = 341, height = 411 },
				spriteSourceSize = { width = 341, height = 411 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-4",
				spriteColorRect = { x = 11, y = 34, width = 341, height = 403 },
				textureRect = { x = 2, y = 2, width = 341, height = 403 },
				spriteSourceSize = { width = 341, height = 403 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-1",
				spriteColorRect = { x = 38, y = 25, width = 339, height = 423 },
				textureRect = { x = 1026, y = 832, width = 339, height = 423 },
				spriteSourceSize = { width = 339, height = 423 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-2",
				spriteColorRect = { x = 45, y = 17, width = 337, height = 431 },
				textureRect = { x = 1367, y = 836, width = 337, height = 431 },
				spriteSourceSize = { width = 337, height = 431 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-3",
				spriteColorRect = { x = 48, y = 7, width = 339, height = 443 },
				textureRect = { x = 342, y = 1247, width = 339, height = 443 },
				spriteSourceSize = { width = 339, height = 443 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-4",
				spriteColorRect = { x = 44, y = 0, width = 347, height = 451 },
				textureRect = { x = 1033, y = 1269, width = 347, height = 451 },
				spriteSourceSize = { width = 347, height = 451 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-5",
				spriteColorRect = { x = 0, y = 0, width = 391, height = 451 },
				textureRect = { x = 1382, y = 1270, width = 391, height = 451 },
				spriteSourceSize = { width = 391, height = 451 },
				spriteTrimmed = false,
				textureRotated = false
			}
		}
	}
end
return SpriteSheet

