-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:81bb1ff2b5572f6bed6e8ad14e1ba381$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "pi1",
				spriteColorRect = { x = 12, y = 19, width = 398, height = 494 },
				textureRect = { x = 402, y = 1450, width = 398, height = 494 },
				spriteSourceSize = { width = 398, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2",
				spriteColorRect = { x = 11, y = 22, width = 400, height = 492 },
				textureRect = { x = 1216, y = 968, width = 400, height = 492 },
				spriteSourceSize = { width = 400, height = 492 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3",
				spriteColorRect = { x = 10, y = 25, width = 402, height = 488 },
				textureRect = { x = 408, y = 960, width = 402, height = 488 },
				spriteSourceSize = { width = 402, height = 488 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi4",
				spriteColorRect = { x = 9, y = 28, width = 404, height = 486 },
				textureRect = { x = 1638, y = 512, width = 404, height = 486 },
				spriteSourceSize = { width = 404, height = 486 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi5",
				spriteColorRect = { x = 8, y = 30, width = 406, height = 484 },
				textureRect = { x = 822, y = 482, width = 406, height = 484 },
				spriteSourceSize = { width = 406, height = 484 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi6",
				spriteColorRect = { x = 7, y = 34, width = 408, height = 480 },
				textureRect = { x = 2, y = 478, width = 408, height = 480 },
				spriteSourceSize = { width = 408, height = 480 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi7",
				spriteColorRect = { x = 6, y = 36, width = 410, height = 478 },
				textureRect = { x = 826, y = 2, width = 410, height = 478 },
				spriteSourceSize = { width = 410, height = 478 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi8",
				spriteColorRect = { x = 6, y = 40, width = 410, height = 474 },
				textureRect = { x = 2, y = 2, width = 410, height = 474 },
				spriteSourceSize = { width = 410, height = 474 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime1",
				spriteColorRect = { x = 12, y = 19, width = 398, height = 494 },
				textureRect = { x = 802, y = 1458, width = 398, height = 494 },
				spriteSourceSize = { width = 398, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime2",
				spriteColorRect = { x = 11, y = 22, width = 400, height = 492 },
				textureRect = { x = 1618, y = 1000, width = 400, height = 492 },
				spriteSourceSize = { width = 400, height = 492 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime3",
				spriteColorRect = { x = 10, y = 25, width = 402, height = 488 },
				textureRect = { x = 812, y = 968, width = 402, height = 488 },
				spriteSourceSize = { width = 402, height = 488 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime4",
				spriteColorRect = { x = 9, y = 28, width = 404, height = 486 },
				textureRect = { x = 2, y = 960, width = 404, height = 486 },
				spriteSourceSize = { width = 404, height = 486 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime5",
				spriteColorRect = { x = 8, y = 30, width = 406, height = 484 },
				textureRect = { x = 1230, y = 482, width = 406, height = 484 },
				spriteSourceSize = { width = 406, height = 484 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime6",
				spriteColorRect = { x = 7, y = 34, width = 408, height = 480 },
				textureRect = { x = 412, y = 478, width = 408, height = 480 },
				spriteSourceSize = { width = 408, height = 480 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime7",
				spriteColorRect = { x = 6, y = 36, width = 410, height = 478 },
				textureRect = { x = 1238, y = 2, width = 410, height = 478 },
				spriteSourceSize = { width = 410, height = 478 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime8",
				spriteColorRect = { x = 6, y = 40, width = 410, height = 474 },
				textureRect = { x = 414, y = 2, width = 410, height = 474 },
				spriteSourceSize = { width = 410, height = 474 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime1-1",
				spriteColorRect = { x = 6, y = 37, width = 398, height = 494 },
				textureRect = { x = 2, y = 1448, width = 398, height = 494 },
				spriteSourceSize = { width = 398, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime1-2",
				spriteColorRect = { x = 10, y = 24, width = 394, height = 508 },
				textureRect = { x = 1650, y = 2, width = 394, height = 508 },
				spriteSourceSize = { width = 394, height = 508 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime1-3",
				spriteColorRect = { x = 14, y = 12, width = 396, height = 520 },
				textureRect = { x = 1202, y = 1462, width = 396, height = 520 },
				spriteSourceSize = { width = 396, height = 520 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime1-4",
				spriteColorRect = { x = 20, y = 2, width = 408, height = 528 },
				textureRect = { x = 1600, y = 1494, width = 408, height = 528 },
				spriteSourceSize = { width = 408, height = 528 },
				spriteTrimmed = false,
				textureRotated = false
			}
		}
	}
end
return SpriteSheet

