-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:0451fe04949dfe5eb9d6f099163d7f2d$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "prime2-1",
				spriteColorRect = { x = 12, y = 19, width = 398, height = 494 },
				textureRect = { x = 1210, y = 498, width = 398, height = 494 },
				spriteSourceSize = { width = 398, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime2-2",
				spriteColorRect = { x = 13, y = 25, width = 398, height = 490 },
				textureRect = { x = 1216, y = 1516, width = 398, height = 490 },
				spriteSourceSize = { width = 398, height = 490 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime2-3",
				spriteColorRect = { x = 12, y = 33, width = 400, height = 482 },
				textureRect = { x = 1610, y = 494, width = 400, height = 482 },
				spriteSourceSize = { width = 400, height = 482 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime2-4",
				spriteColorRect = { x = 14, y = 40, width = 400, height = 474 },
				textureRect = { x = 1610, y = 978, width = 400, height = 474 },
				spriteSourceSize = { width = 400, height = 474 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime3-1",
				spriteColorRect = { x = 45, y = 30, width = 398, height = 496 },
				textureRect = { x = 810, y = 522, width = 398, height = 496 },
				spriteSourceSize = { width = 398, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime3-2",
				spriteColorRect = { x = 53, y = 20, width = 396, height = 506 },
				textureRect = { x = 808, y = 1056, width = 396, height = 506 },
				spriteSourceSize = { width = 396, height = 506 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime3-3",
				spriteColorRect = { x = 57, y = 10, width = 398, height = 518 },
				textureRect = { x = 464, y = 2, width = 398, height = 518 },
				spriteSourceSize = { width = 398, height = 518 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime3-4",
				spriteColorRect = { x = 51, y = 0, width = 408, height = 530 },
				textureRect = { x = 2, y = 534, width = 408, height = 530 },
				spriteSourceSize = { width = 408, height = 530 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "prime3-5",
				spriteColorRect = { x = 0, y = 0, width = 460, height = 530 },
				textureRect = { x = 2, y = 2, width = 460, height = 530 },
				spriteSourceSize = { width = 460, height = 530 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-1",
				spriteColorRect = { x = 6, y = 37, width = 398, height = 494 },
				textureRect = { x = 1206, y = 1020, width = 398, height = 494 },
				spriteSourceSize = { width = 398, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-2",
				spriteColorRect = { x = 10, y = 24, width = 394, height = 508 },
				textureRect = { x = 412, y = 1056, width = 394, height = 508 },
				spriteSourceSize = { width = 394, height = 508 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-3",
				spriteColorRect = { x = 14, y = 12, width = 396, height = 520 },
				textureRect = { x = 412, y = 534, width = 396, height = 520 },
				spriteSourceSize = { width = 396, height = 520 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi1-4",
				spriteColorRect = { x = 20, y = 2, width = 408, height = 528 },
				textureRect = { x = 2, y = 1066, width = 408, height = 528 },
				spriteSourceSize = { width = 408, height = 528 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-1",
				spriteColorRect = { x = 12, y = 19, width = 398, height = 494 },
				textureRect = { x = 864, y = 2, width = 398, height = 494 },
				spriteSourceSize = { width = 398, height = 494 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-2",
				spriteColorRect = { x = 13, y = 25, width = 398, height = 490 },
				textureRect = { x = 1264, y = 2, width = 398, height = 490 },
				spriteSourceSize = { width = 398, height = 490 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-3",
				spriteColorRect = { x = 12, y = 33, width = 400, height = 482 },
				textureRect = { x = 814, y = 1564, width = 400, height = 482 },
				spriteSourceSize = { width = 400, height = 482 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi2-4",
				spriteColorRect = { x = 14, y = 40, width = 400, height = 474 },
				textureRect = { x = 412, y = 1566, width = 400, height = 474 },
				spriteSourceSize = { width = 400, height = 474 },
				spriteTrimmed = false,
				textureRotated = false
			}
		}
	}
end
return SpriteSheet

