-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:7f5f6e2553df6f39288c0b68bd76affd$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "pi3-1",
				spriteColorRect = { x = 45, y = 30, width = 398, height = 496 },
				textureRect = { x = 402, y = 534, width = 398, height = 496 },
				spriteSourceSize = { width = 398, height = 496 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-2",
				spriteColorRect = { x = 53, y = 20, width = 396, height = 506 },
				textureRect = { x = 402, y = 1032, width = 396, height = 506 },
				spriteSourceSize = { width = 396, height = 506 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-3",
				spriteColorRect = { x = 57, y = 10, width = 398, height = 518 },
				textureRect = { x = 2, y = 534, width = 398, height = 518 },
				spriteSourceSize = { width = 398, height = 518 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-4",
				spriteColorRect = { x = 51, y = 0, width = 408, height = 530 },
				textureRect = { x = 464, y = 2, width = 408, height = 530 },
				spriteSourceSize = { width = 408, height = 530 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pi3-5",
				spriteColorRect = { x = 0, y = 0, width = 460, height = 530 },
				textureRect = { x = 2, y = 2, width = 460, height = 530 },
				spriteSourceSize = { width = 460, height = 530 },
				spriteTrimmed = false,
				textureRotated = false
			}
		}
	}
end
return SpriteSheet

